### ISSUE TITLE
If you already live in production

### ISSUE THREAD

**Issue by zhiephie** [redound/phalcon-rest-boilerplate#10]
how for the first time of initial authentication user login

because, I tried the results like this: http://prntscr.com/9z9ry3

**Comment by andevsoftware** [comment]
Hi,

You need to make a post request to
http://localhost:8088/phalcon-rest-boilerplate/users/authenticate and pass your username and password along as authorization header (demo:test123) should be (Authorization Basic ZGVtbzp0ZXN0MTIz). It will return a authToken which you can use to authenticate the next requests.
You may also want to look at this page: http://www.phalcon-rest.org/docs/concepts/authentication.html

Try downloading the postman extension, it's is a good tool for testing your endpoints.
then import http://localhost:8088/phalcon-rest-boilerplate/export/postman.json as a collection.

**Comment by zhiephie** [comment]
Thanks @olivierandriessen

**Comment by andevsoftware** [comment]
@zhiephie You're welcome ;)
