### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by kenpb** [redound/phalcon-rest-boilerplate#11]
Hello!,

I have a couple of questions, I'm supposed to send the post to /users/authenticate/username right?, or is it to /users/authenticate, I've tried both endpoints and I'm getting a `"General: Not found"` and a `"Auth: Bad login credentials"`, respectively.

Now, trying stuff out I thought that maybe the DB will be the problem, I've discovered that not matter the configuration of my db in the server.develop.php, it doesn't seem to make any difference, no errors are thrown, any thoughts?, I have no idea what I'm doing wrong.

This is the code I'm using to test it.
Thanks!

``` php
<?php
$url = 'http://localhost/phalcon-rest-boilerplate/users/authenticate/';

//$header = ["Authorization: 'Basic ZGVtbzp0ZXN0MTIz'"];
$header = ["Authorization: 'Basic " . base64_encode("demo:test123") . "'"];

$ch = curl_init();

curl_setopt($ch, CURLOPT_VERBOSE, TRUE);
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_HEADER, TRUE);
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLINFO_HEADER_OUT, TRUE);

$response = curl_exec($ch);
echo PHP_EOL;
echo "Request: " . PHP_EOL;
echo curl_getinfo($ch, CURLINFO_HEADER_OUT);    
echo PHP_EOL;

echo "Response:" . PHP_EOL;
echo $response; 
echo PHP_EOL;

curl_close($ch);
```

**Comment by andevsoftware** [comment]
Hi, the `/users/authenticate` together with `Auth: Bad login credentials` is the right response. I recommend you debug `UserController` and the `UsernameAccountType#login(data)` implementation, where the data should contain the credentials you've given. That's where the user is being authenticated. It could be anything from not getting the username and password from the header to your database connection like you said. Perhaps `$url = 'http://localhost/phalcon-rest-boilerplate/users/authenticate/';` the trailing slash makes a difference. Let me know if you have any other questions.

**Comment by kenpb** [comment]
Hey @olivierandriessen, thanks for your response!,

I've found an answer to my problem, and also wanna point out that for some reason I wasn't able to debug the client I was using so I end up using a third party program to make the post request.

The problem was the `$header = ["Authorization: 'Basic ZGVtbzp0ZXN0MTIz'"];` and/or `
$header = ["Authorization: 'Basic " . base64_encode("demo:test123") . "'"];` the `'Basic ZGVtbzp0ZXN0MTIz'` shouldn't be enclosed by single quotes.

I'm not quite sure where I got that from but I think that I misunderstood the comment on the authenticate function of the user controller.

Thanks again,
Cheers!

**Comment by andevsoftware** [comment]
Hey @kenpb, Glad you found out. I can admit that the documentation isn't at it's best stage yet, mainly because of the newest release (1.2.1). It just has been released, a lot of improvements have been made including several essential features. Good luck with your project!
