### ISSUE TITLE
"Strict standards: Declaration" on initial load.

### ISSUE THREAD

**Issue by zyxep** [redound/phalcon-rest-boilerplate#13]
Hi guys.

I get this, https://i.imgur.com/TTpP2jQ.png just after a clone of boilerplate & composer update/install.

APPLICATION_ENV variable has been set, i have changed config files.

**Comment by andevsoftware** [comment]
Hi @zyxep, how is your environment set up? Are you running at least php 5.6 with phalcon 2.0.0?

**Comment by sergeyklay** [comment]
Hello @olivierandriessen 

It seems to me this is Strict Standard warning, no environment issue. 

``` php
namespace App {
    class Bootstrap {
        public function run(...$args) {
            ...
        }
    }
}

namespace App\Bootstrap {
    class ServiceBootstrap extends \App\Bootstrap {
        public function run(Api $api, DiInterface $di, Config $config) {
            ...
        }
    }
}

```

Declaration of `ServiceBootstrap::run` should be compatible with `\App\Bootstrap::run`. These warnings means that there are certain possible method calls which may fail at run-time.

This is obvious error in the design. As workaround you can use `func_get_args()` into `ServiceBootstrap::run`.

**Comment by andevsoftware** [comment]
@sergeyklay Thanks for your help. It wasn't necessary to extend them in the first place, for convienence I added the `BootstrapInterface`. Do you have any tips for improving the bootstrap design?

@zyxep I've updated so that the warnings shouldn't be showing anymore.
