### ISSUE TITLE
How about tests guys ?

### ISSUE THREAD

**Issue by sergeyklay** [redound/phalcon-rest-boilerplate#15]

**Comment by andevsoftware** [comment]
@sergeyklay It would be nice to have them, what would you recommend for testing?

**Comment by sergeyklay** [comment]
First [Codeception functional](http://codeception.com/docs/04-FunctionalTests) and [RESTful](http://codeception.com/docs/modules/REST) tests.

For example:
- https://github.com/ovide/phest/blob/master/tests/functional/Rest/AcceptCest.php
- https://github.com/stanislav-web/Phalcon-development/tree/Rest/tests/api/Rest

**Comment by andevsoftware** [comment]
Alright, looks promising. Thanks! I've set up Codeception and added some unit tests. (dev-tests branch). I agree functional test can be quite helpful to begin with. Let me know if you have suggestions on how it's set up.

**Comment by sergeyklay** [comment]
Just start doing it. I shall prompt, if the need arises
