### ISSUE TITLE
example

### ISSUE THREAD

**Issue by Chriscxa** [redound/phalcon-rest-boilerplate#16]
Hi,

I´m new and is hard to understand.
if anyone have time, can fork this with an working frontend-example?
many thanx.

**Comment by sergeyklay** [comment]
@Chriscxa http://phalcon-rest.redound.org/

**Comment by Chriscxa** [comment]
sure, but nothing works.
I installed without "errors" on xampp via composer.
Is anywhere a config or similar?

**Comment by andevsoftware** [comment]
@Chriscxa Could you elaborate how your environment is set up? Do you have at least PHP 5.6 and Phalcon 2.0.0 installed?

**Comment by Chriscxa** [comment]
sure. use lastest phalcon and php 5.6~ (clean xampp installation)
But can´t access "OK"-page like demovideo (http://phalcon-rest.redound.org/).
My question is: i need somewhere to make settings? 

My error is:
{"error":{"code":0,"message":"Trying to call method send on a non-object","developer":{"file":"F:\xampp\htdocs\phalcon-rest-boilerplate-master\public\index.php","line":80,"request":"GET \/phalcon-rest-boilerplate-master\/"}}}

**Comment by sergeyklay** [comment]
Enable please error reporting (in php.ini) an provide logs entries after request to the demo application (full error stack).

**Comment by sergeyklay** [comment]
@Chriscxa this is Phalcon bug. See https://github.com/phalcon/cphalcon/pull/11574

**Comment by sergeyklay** [comment]
@Chriscxa http://phalcon-rest.redound.org/quick_start.html

**Comment by Chriscxa** [comment]
oh man. Many many thanx for your time. great!

**Comment by sergeyklay** [comment]
@olivierandriessen It seems to me it may be closed
