### ISSUE TITLE
Fatal error: Call to undefined method PhalconRest\Api::collection()

### ISSUE THREAD

**Issue by zyxep** [redound/phalcon-rest-boilerplate#17]
Hi @olivierandriessen , 

i just pulled the changes from #13 and now i get.

https://i.imgur.com/Nlf2wEI.png

**Comment by andevsoftware** [comment]
@zyxep Yesterday version 1.3.0 got released. You probably need to update `composer update`

**Comment by zyxep** [comment]
Thanks @olivierandriessen that actually worked, pretty sure i did a composer update :) but apparently not.

**Comment by zyxep** [comment]
btw, maybe hang out on Phalcon Slack community? http://chat.phalcontip.com/
