### ISSUE TITLE
Model Properties access based on ACL

### ISSUE THREAD

**Issue by titonobre** [redound/phalcon-rest-boilerplate#23]
Hello.

Nice work you have here. Thank you for that.

I started modifying this boilerplate to fit my needs but I would like to hide some properties for some roles (or show them only to certain roles).
For now, my best option is to modify the method ModelTransformer::excludedProperties() to change the excluded properties according to the current user role. Is there any other way?

Thank you for your attention.

**Comment by andevsoftware** [comment]
@titonobre Hi, thanks :). That would be the preferred way at the moment. By checking the role inside the transformer adjusting the excluded properties based on that role. Another approach would be to create different transformers and delegate each transformer to every other role. It depends on your needs.

**Comment by titonobre** [comment]
@olivierandriessen Thank you. :+1: Keep up the good work.
