### ISSUE TITLE
Using with Nginx

### ISSUE THREAD

**Issue by franciscoernestoteixeira** [redound/phalcon-rest-boilerplate#26]
Hello,

Do you have the code of .htaccess to Nginx?

Thanks a lot!

**Comment by aisuhua** [comment]
Nginx don't support .htaccess. But you can use Nginx rewrite rules to do the same. Please see [Creating NGINX Rewrite Rules](https://www.nginx.com/blog/creating-nginx-rewrite-rules/)

If you want to start up this project or you can see the phalcon document about [Nginx Installation Notes](https://docs.phalconphp.com/en/latest/reference/nginx.html).

**Comment by kfreiman** [comment]
@netinhoteixeira, it works fine with cofig described at [Nginx Installation Notes.](https://docs.phalconphp.com/en/latest/reference/nginx.html)
