### ISSUE TITLE
Nginx setting

### ISSUE THREAD

**Issue by HolmesPaul** [redound/phalcon-rest-boilerplate#28]
Hi,
The .htaccess setting is :
# IMPORTANT TO GET JWT FROM HEADERS

RewriteCond %{HTTP:Authorization} ^(._)
RewriteRule ._ - [e=HTTP_AUTHORIZATION:%1]

how change to nginx setting.???

**Comment by kfreiman** [comment]
@HolmesPaul, it works fine with cofig described at [Nginx Installation Notes.](https://docs.phalconphp.com/en/latest/reference/nginx.html)
