### ISSUE TITLE
Testing Login - still failing

### ISSUE THREAD

**Issue by reubenbrown13** [redound/phalcon-rest-boilerplate#3]
I modified a test script to allow me to test the API, and I can get it to register a user, and activate a user, but when I try to authenticate it returns: {"error":{"code":3008,"status":400,"developer":null,"message":"Auth: Invalid authentication bearer type"}}

I have tried to debug this issue and it seems like the getAccount() function is getting the username value instead of the bearer type.    Below is the code I am using for the test:

``` php
<?php
if (!function_exists('curl_init')) {
    die('Curl module not installed!' . PHP_EOL);
}

$route = '/users/authenticate/testuser';

if (isset($argv[1])) {
    $host = 'http://' . $argv[1] . $route;
} else {
    $host = "http://api.example" . $route;
}

$headers = ["Authorization: 'Basic ".base64_encode("testuser:testpass")."'"];
$ch = curl_init();

curl_setopt($ch, CURLOPT_VERBOSE, TRUE);
curl_setopt($ch, CURLOPT_URL, $host);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_HEADER, TRUE);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLINFO_HEADER_OUT, TRUE);

$result = curl_exec($ch);
if ($result === FALSE) {
    echo "Curl Error: " . curl_error($ch);
} else {
    echo PHP_EOL;
    echo "Request: " . PHP_EOL;
    echo curl_getinfo($ch, CURLINFO_HEADER_OUT);    
    echo PHP_EOL;

    echo "Response:" . PHP_EOL;
    echo $result; 
    echo PHP_EOL;
}
curl_close($ch);
?>
```

Thanks.

**Comment by andevsoftware** [comment]
@reubenbrown13 That's right. The _Invalid authentication bearer type_ error is showing because the route has to be _/users/authenticate/username_ instead of _/users/authenticate/testuser_ (this implies the bearer, username, not the username of the user, testuser). Alternatively you can use _/users/authenticate/google_ to authenticate a Google session.
