### ISSUE TITLE
Class 'PhalconRest\Collection\ResourceCollection' not found

### ISSUE THREAD

**Issue by phil-schreiber** [redound/phalcon-rest-boilerplate#31]
Hi,

after composing the boilerplate according to guide I get the:
`Class 'PhalconRest\Collection\ResourceCollection' not found`
error in:
`phalcon-rest-boilerplate\app\bootstrap\collections.php on line 3`

The according composer libraries are there in folder vendor/phalcon-rest/src/PhalconRest but I too can't find the said class. Maybe some composer misconfiguration after the last merge?

Would be great to get a hint on that one.

Thanks
Phil

**Comment by phil-schreiber** [comment]
Resolved:
Composer pulled an old version by default. Now managed to pull the current version.

**Comment by andevsoftware** [comment]
@phil-schreiber Alright! Glad it worked out.

**Comment by phil-schreiber** [comment]
@olivierandriessen Sry for opening an issue on that, but I seemed to have run out of options. 
Anyway, great work you're doing there. Really like it.
