### ISSUE TITLE
"Collection requires a main handler" error after update to 1.5.0

### ISSUE THREAD

**Issue by vip9** [redound/phalcon-rest-boilerplate#36]
I've created fresh testing env, GET / (or any other URL) generates:
{"error":{"code":0,"message":"Collection requires a main handler","developer":{"file":"phalcon\/mvc\/micro.zep","line":374,"request":"GET \/phalcon-rest-boilerplate\/"}}}

**Comment by andevsoftware** [comment]
@vip9 You have to provide a handler (https://github.com/redound/phalcon-rest-boilerplate/blob/master/app/library/App/Resources/AlbumResource.php#L24) or use the factory method of resource (https://github.com/redound/phalcon-rest/blob/master/src/PhalconRest/Api/Resource.php#L49)

**Comment by andevsoftware** [comment]
@vip9 The boilerplate should work
