### ISSUE TITLE
Documentation does not display all endpoints

### ISSUE THREAD

**Issue by Elenthar** [redound/phalcon-rest-boilerplate#37]
Documentation (documentation.html / postman.json / documentation.json) does not display all endpoints; for example for "User" resource it's not showing "/me" endpoint.

**Comment by Elenthar** [comment]
nvm, figured it out.

**Comment by Yakovlev-Melarn** [comment]
How to solve it?

**Comment by konrad-ch** [comment]
https://github.com/redound/phalcon-rest-boilerplate/issues/43
