### ISSUE TITLE
In the documentation page, Collection add multiple ApiEndpoint only show the last one, how to fix this problem?

### ISSUE THREAD

**Issue by aprchen** [redound/phalcon-rest-boilerplate#43]
在documentation页面中,Collection添加多个ApiEndpoint 只显示最后一个,怎么修复这个问题呢?
In the documentation page, Collection add multiple ApiEndpoint only show the last one, how to fix this problem?

**Comment by konrad-ch** [comment]
Try assigning unique names for every endpoint

**Comment by odat** [comment]
yes i get the same issue

**Comment by odat** [comment]
Updated, you can make this : 
     ```

   ->endpoint(ApiEndpoint::get('/me', 'me')
                ->allow(AclRoles::USER)
                ->description('Returns the currently logged in user')
                ->name("me1")  )

```

**Comment by aprchen** [comment]
@odat Thanks, it worked
