### ISSUE TITLE
raw SQL/PHQL

### ISSUE THREAD

**Issue by ghost** [redound/phalcon-rest-boilerplate#48]
Hello everyone, 
First of all, CONGRATULATIONS for this amazing boilerplate!

I've a huge doubt about SQL execution.
I'd like to execute RAW SQL statements or even PHQL on my controllers/models. But I can't find a way to make it works and there's no example in the project using a raw PHQL in the current controllers/models.

Could someone guide me please?

Thank you advance!

**Comment by naaness** [comment]
Hi man, you can try the next...

Add services on App/library/App/Bootstrap/ServiceBootstrap.php 

`$di->set('modelsManager', function() {
      return new Phalcon\Mvc\Model\Manager();
    });`

end 

`$di->set('modelsMetadata', function() {
      return new \Phalcon\Mvc\Model\MetaData\Memory();
    });`

And then you can use it in the controllers

`$this->modelsManager->createBuilder()
      ->columns(['*'])
      ->from(['users'=> 'App\Model\Users'])
      ->where('users.role = :role:',array('role' => "User"))
      ->getQuery()
      ->execute()`

Good luck man!!

**Comment by ghost** [comment]
It works! Thank you VERY much Naaness.
