### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Thyoity** [redound/phalcon-rest-boilerplate#8]
I imported your schema.sql and tried to use this project. But this error persists:
http://prntscr.com/9e57lr

I think I'm not inserting the user record correctly.

How should I fill the password field? I'm inserting as a plain text for testing purposes.
http://prntscr.com/9e5eeh

**Comment by andevsoftware** [comment]
@Thyoity  Nice, you got it going. It's sha1 password,

Replace the plain text password with this: $2y$10$1/U1yo5yMdXsrsU3RaeULu7dm7UFX1qq3rnfpbQugv7uIPdo2kMcC

Password is **test123** and you should be able to receive a token.

**Comment by Thyoity** [comment]
That's it! Worked great! I changed to work with e-mail instead of username. (for e-mail login)
You can close this issue now, if I have more questions, I'll open another issue. Thanks!

Oh, and one more thing, the encryption is not sha1, it's bcrypt.

**Comment by andevsoftware** [comment]
@Thyoity That's great. You're right, we changed it to bcrypt recently.

PS Currently I'm working on a query syntax for offset, limit, fields, where etc. It will release in the coming days, including documentation.

**Comment by Thyoity** [comment]
I'm waiting anxiously for this release. Thank you!

**Comment by andevsoftware** [comment]
@Thyoity Good news! I just released the url query feature. Let me know if you have any questions ;)

**Comment by Thyoity** [comment]
Great! I'll try to use this feature, and if I have any question, I'll open another issue here.
